version: '3.8'
services:

  nextjs_app:
    image: simple2b/fmc-frontend:v1
    build: .
    volumes:
      - .:/app
    command: yarn run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}