version: '3.8'
services:

  nextjs_app:
    image: simple2b/fmc-frontend
    build: .
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}