version: '3.8'
services:

  nextjs_app:
    image: 270968290167.dkr.ecr.us-east-1.amazonaws.com/fmc-frontend
    build: .
    command: node server.js
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
