version: '3.8'
services:

  nextjs_app:
    image: simple2b/fmc-frontend:v1
    build: .
    command: node server.js
    ports:
      - 127.0.0.1:3000:3000
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
