import { TermsLogo } from '@/common/terms_logo/TermsLogo';
import { TermsLi } from '@/common/terms_wrapper/TermsLi';
import { TermsSubTitle } from '@/common/terms_wrapper/TermsSubTitle';
import { TermsText } from '@/common/terms_wrapper/TermsText';
import { TermsTitle } from '@/common/terms_wrapper/TermsTitle';
import { TermsWrapper } from '@/common/terms_wrapper/TermsWrapper';
import Link from 'next/link';

export default function Privacy() {
  return (
    <>
      <TermsLogo />
      <TermsWrapper>
        <div
          style={{
            borderRight: '1px solid #B5B5B5',
            paddingLeft: '106px',
            paddingRight: '36px',
            marginBottom: '12px',
          }}
        >
          <div style={{ marginBottom: '12px' }}>
            <h1
              style={{
                fontStyle: 'normal',
                fontWeight: 600,
                fontSize: '32px',
                lineHeight: '130%',
              }}
            >
              Privacy Policy
            </h1>
          </div>
          <div style={{ width: '263px' }}>
            <div style={{ marginBottom: '36px' }}>
              <p>Last updated: 27/03/2023.</p>
            </div>
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You. We use Your Personal data to provide and improve
              the Service. By using the Service, You agree to the collection and
              use of information in accordance with this Privacy Policy. This
              Privacy Policy was generated by
              <Link href="/sign_up/terms">TermsFeed</Link> and fine-tuned by
              Sharetribe. Please read this Privacy Policy carefully before using
              Our Service.
            </p>
          </div>
        </div>
        <div
          style={{
            paddingLeft: '58px',
            paddingRight: '69px',
            paddingBottom: '96px',
          }}
        >
          <TermsTitle>1 - Interpretation and Definitions</TermsTitle>
          <TermsSubTitle>1.1 - Interpretation</TermsSubTitle>
          <TermsText>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in the
            singular or in the plural.
          </TermsText>
          <TermsSubTitle>1.2 - Definitions</TermsSubTitle>
          <TermsText>For the purposes of this Privacy Policy:</TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Account means a unique account created for You to access our
              Service or parts of our Service
            </TermsLi>
            <TermsLi>
              Affiliate means an entity that controls, is controlled by, or is
              under common control with a party, where "control" means ownership
              of 50% or more of the shares, equity interest, or other securities
              entitled to vote for the election of directors or other managing
              authority.
            </TermsLi>
            <TermsLi>
              Application means the software program provided by the Company or
              Operator downloaded by You on any electronic device, named
              FindMyCoach
            </TermsLi>
            <TermsLi>
              Business refers to the Company or Operator as the legal entity
              that collects Consumers' personal information and determines the
              purposes and means of the processing of Consumers' personal
              information, or on behalf of which such information is collected
              and that alone, or jointly with others, determines the purposes
              and means of the processing of consumers' personal information.
            </TermsLi>
            <TermsLi>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to FindMyCoach Ltd, 105 Edith Road, West
              Kensington, London, W14 0TJ, -- 14204590.. For the purpose of the
              GDPR, the Company or Operator is the Data Controller.
            </TermsLi>
            <TermsLi>Consumer, refers to You</TermsLi>
            <TermsLi>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </TermsLi>
            <TermsLi>Country refers to United Kingdom.</TermsLi>
            <TermsLi>
              Data Controller, for the purposes of the GDPR (General Data
              Protection Regulation), refers to the Company or Operator as the
              legal person which alone or jointly with others determines the
              purposes and means of the processing of Personal Data.
            </TermsLi>
            <TermsLi>
              Device means any device that can access the Service such as a
              computer, a cellphone, or a digital tablet.
            </TermsLi>
            <TermsLi>
              Do Not Track (DNT) is a concept that has been promoted by US
              regulatory authorities, in particular the U.S. Federal Trade
              Commission (FTC), for the Internet industry to develop and
              implement a mechanism for allowing internet users to control the
              tracking of their online activities across websites.
            </TermsLi>
            <TermsLi>
              Operator (referred to as either "the Operator", "We", "Us" or
              "Our" in this Agreement) refers to FindMyCoach. For the purpose of
              the GDPR, the Company or Operator is the Data Controller.
            </TermsLi>
            <TermsLi>
              Personal Data is any information that relates to an identified or
              identifiable individual. For the purposes of GDPR, Personal Data
              means any information relating to You such as a name, an
              identification number, location data, online identifier or to one
              or more factors specific to the physical, physiological, genetic,
              mental, economic, cultural or social identity. For the purposes of
              the CCPA, Personal Data means any information that identifies,
              relates to, describes or is capable of being associated with, or
              could reasonably be linked, directly or indirectly, with You.
            </TermsLi>
            <TermsLi>
              Sale, means selling, renting, releasing, disclosing,
              disseminating, making available, transferring, or otherwise
              communicating orally, in writing, or by electronic or other means,
              a Consumer's personal information to another business or a third
              party for monetary or other valuable consideration.
            </TermsLi>
            <TermsLi>
              Service refers to the Application or the Website or both.
            </TermsLi>
            <TermsLi>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company or Operator. It refers to
              third-party companies or individuals employed by the Company or
              Operator to facilitate the Service, to provide the Service on
              behalf of the Company or Operator, to perform services related to
              the Service or to assist the Company or Operator in analyzing how
              the Service is used. For the purpose of the GDPR, Service
              Providers are considered Data Processors.
            </TermsLi>
            <TermsLi>
              Third-party Social Media Service refers to any website or any
              social network website through which a User can log in or create
              an account to use the Service.
            </TermsLi>
            <TermsLi>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </TermsLi>

            <TermsLi>
              Website refers to FindMyCoach Ltd, accessible from
              <Link href="#"> www.findmycoach.co.uk.</Link>
            </TermsLi>
            <TermsLi>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable. Under GDPR
              (General Data Protection Regulation), You can be referred to as
              the Data Subject or as the User as you are the individual using
              the Service.
            </TermsLi>
          </ul>
          <TermsTitle>2 - Contact Us</TermsTitle>
          <TermsText>
            If you have any questions about these Terms of Service, You can
            contact us: By email:
            <span style={{ color: '#F05547' }}>info@findmycoach.co.uk</span>
          </TermsText>

          <TermsTitle>3 - Collecting and Using Your Personal Data</TermsTitle>
          <TermsSubTitle>3.1 - Types of Data Collected</TermsSubTitle>
          <TermsSubTitle>3.1.1 - Personal Data</TermsSubTitle>

          <TermsText>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>Email address</TermsLi>
            <TermsLi>First name and last name</TermsLi>
            <TermsLi>Phone number</TermsLi>
            <TermsLi>Address, State, Province, ZIP/Postal code, City</TermsLi>
            <TermsLi>Bank account information</TermsLi>
            <TermsLi>
              Credit card or debit card number and expiration date
            </TermsLi>
            <TermsLi>Usage Data</TermsLi>
          </ul>

          <TermsSubTitle>3.1.1 - Personal Data</TermsSubTitle>

          <TermsText>
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as Your Device's Internet Protocol
            address (e.g. IP address), browser type, browser version, the pages
            of our Service that You visit, the time and date of Your visit, the
            time spent on those pages, unique device identifiers and other
            diagnostic data.
          </TermsText>
          <TermsText>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </TermsText>
          <TermsText>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </TermsText>
          <TermsSubTitle>
            3.1.3 - Information from Third-Party Social Media Services
          </TermsSubTitle>
          <TermsText>
            The Company or Operator may allow You to create an account and log
            in to use the Service through the following Third-party Social Media
            Services. These Third-party Social Media Services, may include, but
            is not limited to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>Google</TermsLi>
            <TermsLi>Facebook</TermsLi>
            <TermsLi>Twitter</TermsLi>
            <TermsLi>LinkedIn</TermsLi>
            <TermsLi>Apple</TermsLi>
          </ul>
          <TermsText>
            If You decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, We may collect Personal data that
            is already associated with Your Third-Party Social Media Service's
            account, such as Your name, Your email address, Your activities or
            Your contact list associated with that account. You may also have
            the option of sharing additional information with the Company or
            Operator through Your Third-Party Social Media Service's account. If
            You choose to provide such information and Personal Data, during
            registration or otherwise, You are giving the Company or Operator
            permission to use, share, and store it in a manner consistent with
            this Privacy Policy.
          </TermsText>
          <TermsSubTitle>
            3.1.4 - Tracking Technologies and Cookies
          </TermsSubTitle>
          <TermsText>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Cookies or Browser Cookies. A cookie is a small file placed on
              Your Device. You can instruct Your browser to refuse all Cookies
              or to indicate when a Cookie is being sent. However, if You do not
              accept Cookies, You may not be able to use some parts of our
              Service. Unless you have adjusted Your browser setting so that it
              will refuse Cookies, our Service may use Cookies.
            </TermsLi>
            <TermsLi>
              Web Beacons. Certain sections of our Service and our emails may
              contain small electronic files known as web beacons (also referred
              to as clear gifs, pixel tags, and single-pixel gifs) that permit
              the Company or Operator, for example, to count users who have
              visited those pages or opened an email and for other related
              application or website statistics (for example, recording the
              popularity of a certain section and verifying system and server
              integrity). Cookies can be "Persistent" or "Session" Cookies.
              Persistent Cookies remain on Your personal computer or mobile
              device when You go offline, while Session Cookies are deleted as
              soon as You close Your web browser. We use both Session and
              Persistent Cookies for the purposes set out below:
            </TermsLi>
            <TermsLi>
              Necessary / Essential Cookies Type: Session Cookies Administered
              by: Us Purpose: These Cookies are essential to provide You with
              services available through the Application or Website and to
              enable You to use some of its features. They help to authenticate
              users and prevent fraudulent use of user accounts. Without these
              Cookies, the services that You have asked for cannot be provided,
              and We only use these Cookies to provide You with those services.
            </TermsLi>
            <TermsLi>
              Cookies Policy / Notice Acceptance Cookies Type: Persistent
              Cookies Administered by: Us Purpose: These Cookies identify if
              users have accepted the use of cookies on the Application or
              Website.
            </TermsLi>
            <TermsLi>
              Functionality Cookies Type: Persistent Cookies Administered by: Us
              Purpose: These Cookies allow us to remember choices You make when
              You use the Application or Website, such as remembering your login
              details or language preference. The purpose of these Cookies is to
              provide You with a more personal experience and to avoid You
              having to re-enter your preferences every time You use the
              Application or Website.
            </TermsLi>
            <TermsLi>
              Tracking and Performance Cookies Type: Persistent Cookies
              Administered by: Third-Parties Purpose: These Cookies are used to
              track information about traffic to the Application or Website and
              how users use the Application or Website. The information gathered
              via these Cookies may directly or indirectly identify you as an
              individual visitor. This is because the information collected is
              typically linked to a pseudonymous identifier associated with the
              device you use to access the Application or Website. We may also
              use these Cookies to test new pages, features or new functionality
              of the Application or Website to see how our users react to them.
            </TermsLi>
          </ul>
          <TermsSubTitle>3.2 - Use of Your Personal Data</TermsSubTitle>
          <TermsText>
            The Company or Operator may use Personal Data for the following
            purposes:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              To provide and maintain our Service, including to monitor the
              usage of our Service.
            </TermsLi>
            <TermsLi>
              To manage Your Account: to manage Your registration as a user of
              the Service. The Personal Data You provide can give You access to
              different functionalities of the Service that are available to You
              as a registered user.
            </TermsLi>
            <TermsLi>
              For the performance of a contract: the development, compliance and
              undertaking of the purchase contract for the products, items or
              services You have purchased or of any other contract with Us
              through the Service.
            </TermsLi>
            <TermsLi>
              To contact You: To contact You by email, telephone calls, SMS, or
              other equivalent forms of electronic communication, such as a
              mobile application's push notifications regarding updates or
              informative communications related to the functionalities,
              products or contracted services, including the security updates,
              when necessary or reasonable for their implementation.
            </TermsLi>
            <TermsLi>
              To provide You with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless You have opted not to receive such information.
            </TermsLi>
            <TermsLi>
              To manage Your requests: To attend and manage Your requests to Us.
            </TermsLi>
            <TermsLi>
              To deliver targeted advertising to You: We may use Your
              information to develop and display content and advertising (and
              work with third-party vendors who do so) tailored to Your
              interests and/or location and to measure its effectiveness.
            </TermsLi>
            <TermsLi>
              For business transfers: We may use Your information to evaluate or
              conduct a merger, divestiture, restructuring, reorganization,
              dissolution, or other sale or transfer of some or all of Our
              assets, whether as a going concern or as part of bankruptcy,
              liquidation, or similar proceeding, in which Personal Data held by
              Us about our Service users is among the assets transferred.
            </TermsLi>
            <TermsLi>
              For other purposes: We may use Your information for other
              purposes, such as data analysis, identifying usage trends,
              determining the effectiveness of our promotional campaigns and to
              evaluate and improve our Service, products, services, marketing
              and your experience.
            </TermsLi>
          </ul>
          <TermsText>
            We may share Your personal information in the following situations:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              With Service Providers: We may share Your personal information
              with Service Providers to monitor and analyze the use of our
              Service, to advertise on third party websites to You after You
              visited our Service, for payment processing, to contact You.
            </TermsLi>
            <TermsLi>
              For business transfers: We may share or transfer Your personal
              information in connection with, or during negotiations of, any
              merger, sale of Company or Operator assets, financing, or
              acquisition of all or a portion of Our business to another
              company.
            </TermsLi>
            <TermsLi>
              With Affiliates: We may share Your information with Our
              affiliates, in which case we will require those affiliates to
              honor this Privacy Policy. Affiliates include Our parent company
              and any other subsidiaries, joint venture partners or other
              companies that We control or that are under common control with
              Us.
            </TermsLi>
            <TermsLi>
              With business partners: We may share Your information with Our
              business partners to offer You certain products, services or
              promotions.
            </TermsLi>
            <TermsLi>
              With other users: when You share personal information or otherwise
              interact in the public areas with other users, such information
              may be viewed by all users and may be publicly distributed
              outside. If You interact with other users or register through a
              Third-Party Social Media Service, Your contacts on the Third-Party
              Social Media Service may see Your name, profile, pictures and
              description of Your activity. Similarly, other users will be able
              to view descriptions of Your activity, communicate with You and
              view Your profile.
            </TermsLi>
            <TermsLi>
              With Your consent: We may disclose Your personal information for
              any other purpose with Your consent.
            </TermsLi>
          </ul>
          <TermsSubTitle>3.3 - Retention of Your Personal Data</TermsSubTitle>
          <TermsText>
            The Company or Operator will retain Your Personal Data only for as
            long as is necessary for the purposes set out in this Privacy
            Policy. We will retain and use Your Personal Data to the extent
            necessary to comply with our legal obligations (for example, if we
            are required to retain your data to comply with applicable laws),
            resolve disputes, and enforce our legal agreements and policies.
          </TermsText>
          <TermsText>
            The Company or Operator will also retain Usage Data for internal
            analysis purposes. Usage Data is generally retained for a shorter
            period of time, except when this data is used to strengthen the
            security or to improve the functionality of Our Service, or We are
            legally obligated to retain this data for longer time periods. When
            Your Personal Data is no longer required by law or rights or
            obligations by Us or You, We will delete the Personal Data. In most
            cases, Personal Data will be deleted upon termination or expiry of
            the agreement between the You and the Company or Operator or upon
            Your written request.
          </TermsText>
          <TermsSubTitle>3.4 - Transfer of Your Personal Data</TermsSubTitle>
          <TermsText>
            Your information, including Personal Data, is processed at the
            Company’s or Operator's operating offices and in any other places
            where the parties involved in the processing are located. It means
            that this information may be transferred to — and maintained on —
            computers located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            from those from Your jurisdiction. Your consent to this Privacy
            Policy followed by Your submission of such information represents
            Your agreement to that transfer.
          </TermsText>
          <TermsText>
            The Company or Operator will take all steps reasonably necessary to
            ensure that Your data is treated securely and in accordance with
            this Privacy Policy and no transfer of Your Personal Data will take
            place to an organization or a country unless there are adequate
            controls in place including the security of Your data and other
            personal information.
          </TermsText>
          <TermsSubTitle>3.5 - Delete Your Personal Data</TermsSubTitle>
          <TermsText>
            You have the right to delete or request that We assist in deleting
            the Personal Data that We have collected about You. Our Service may
            give You the ability to delete certain information about You from
            within the Service. You may update, amend, or delete Your
            information at any time by signing in to Your Account, if you have
            one, and visiting the account settings section that allows you to
            manage Your personal information. You may also contact Us to request
            access to, correct, or delete any personal information that You have
            provided to Us. Please note, however, that We may need to retain
            certain information when we have a legal obligation or lawful basis
            to do so.
          </TermsText>
          <TermsSubTitle>3.6 - Disclosure of Your Personal Data</TermsSubTitle>
          <TermsSubTitle>3.6.1 - Business Transactions</TermsSubTitle>
          <TermsText>
            If the Company or Operator is involved in a merger, acquisition or
            asset sale, Your Personal Data may be transferred. We will provide
            notice before Your Personal Data is transferred and becomes subject
            to a different Privacy Policy.
          </TermsText>
          <TermsSubTitle>3.6.2 - Law enforcement</TermsSubTitle>
          <TermsText>
            Under certain circumstances, the Company or Operator may be required
            to disclose Your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court or a
            government agency).
          </TermsText>
          <TermsSubTitle>3.6.3 - Other legal requirements</TermsSubTitle>
          <TermsText>
            The Company or Operator may disclose Your Personal Data in the good
            faith belief that such action is necessary to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>Comply with a legal obligation</TermsLi>
            <TermsLi>
              Protect and defend the rights or property of the Company or
              Operator
            </TermsLi>
            <TermsLi>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </TermsLi>
            <TermsLi>
              Protect the personal safety of Users of the Service or the public
            </TermsLi>
            <TermsLi>Protect against legal liability</TermsLi>
          </ul>
          <TermsSubTitle>3.7 - Security of Your Personal Data</TermsSubTitle>
          <TermsText>
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </TermsText>

          <TermsTitle>
            4 - Detailed Information on the Processing of Your Personal Data
          </TermsTitle>
          <TermsText>
            The Service Providers We use may have access to Your Personal Data.
            These third-party vendors collect, store, use, process and transfer
            information about Your activity on Our Service in accordance with
            their Privacy Policies.
          </TermsText>
          <TermsSubTitle>4.1 - Analytics</TermsSubTitle>
          <TermsText>
            We may use third-party Service providers to monitor and analyze the
            use of our Service. They may include, but are not limited to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Google Analytics Google Analytics is a web analytics service
              offered by Google that tracks and reports website traffic. Google
              uses the data collected to track and monitor the use of our
              Service. This data is shared with other Google services. Google
              may use the collected data to contextualize and personalize the
              ads of its own advertising network. You can opt-out of having made
              your activity on the Service available to Google Analytics by
              installing the Google Analytics opt-out browser add-on. The add-on
              prevents the Google Analytics JavaScript (ga.js, analytics.js and
              dc.js) from sharing information with Google Analytics about visits
              activity. You may opt-out of certain Google Analytics features
              through your mobile device settings, such as your device
              advertising settings or by following the instructions provided by
              Google in their Privacy Policy:
              <Link href="https://policies.google.com/privacy">
                https://policies.google.com/privacy
              </Link>
              For more information on the privacy practices of Google, please
              visit the Google Privacy & Terms web page:
              <Link href="https://policies.google.com/privacy">
                https://policies.google.com/privacy
              </Link>
            </TermsLi>
            <TermsLi>
              Matomo Matomo is a web analytics service. You can visit their
              Privacy Policy page here:
              <Link href="https://matomo.org/privacy-policy">
                https://matomo.org/privacy-policy
              </Link>
            </TermsLi>
            <TermsLi>
              Fathom Fathom is a web analytics service. You can visit their
              Privacy Policy page here:
              <Link href=" https://www.fathomhq.com/privacy">
                https://www.fathomhq.com/privacy
              </Link>
            </TermsLi>
          </ul>
          <TermsSubTitle>4.2 - Email Marketing</TermsSubTitle>
          <TermsText>
            We may use Your Personal Data to contact You with newsletters,
            marketing or promotional materials and other information that may be
            of interest to You. You may opt-out of receiving any, or all, of
            these communications from Us by following the unsubscribe link or
            instructions provided in any email We send or by contacting Us.
          </TermsText>
          <TermsText>
            We may use Email Marketing Service Providers to manage and send
            emails to You. They may include, but are not limited to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Mailchimp Mailchimp is an email marketing sending service provided
              by The Rocket Science Group LLC. For more information on the
              privacy practices of Mailchimp, please visit their Privacy policy:
              <Link href="https://mailchimp.com/legal/privacy/">
                https://mailchimp.com/legal/privacy/
              </Link>
            </TermsLi>
          </ul>
          <TermsSubTitle>4.3 - Payments</TermsSubTitle>
          <TermsText>
            We may provide paid products and/or services within the Service. In
            that case, we may use third-party services for payment processing
            (e.g. payment processors).
          </TermsText>
          <TermsText>
            We will not store or collect Your payment card details. That
            information is provided directly to Our third-party payment
            processors whose use of Your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information.
          </TermsText>
          <TermsText>They may include, but are not limited to:</TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Stripe Their Privacy Policy can be viewed at
              <Link href="https://stripe.com/us/privacy">
                https://stripe.com/us/privacy
              </Link>
            </TermsLi>
            <TermsLi>
              PayPal Their Privacy Policy can be viewed at
              <Link href="https://www.paypal.com/us/webapps/mpp/ua/privacy-full">
                https://www.paypal.com/us/webapps/mpp/ua/privacy-full
              </Link>
            </TermsLi>
          </ul>
          <TermsSubTitle>4.4 - Behavioral Remarketing</TermsSubTitle>
          <TermsText>
            The Company or Operator uses remarketing services to advertise to
            You after You accessed or visited our Service. We and Our
            third-party vendors use cookies and non-cookie technologies to help
            Us recognize Your Device and understand how You use our Service so
            that We can improve our Service to reflect Your interests and serve
            You advertisements that are likely to be of more interest to You.
          </TermsText>
          <TermsText>
            These third-party vendors collect, store, use, process and transfer
            information about Your activity on Our Service in accordance with
            their Privacy Policies and to enable Us to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Measure and analyze traffic and browsing activity on Our Service
            </TermsLi>
            <TermsLi>
              Show advertisements for our products and/or services to You on
              third-party websites or apps
            </TermsLi>
            <TermsLi>
              Measure and analyze the performance of Our advertising campaigns
            </TermsLi>
          </ul>
          <TermsText>
            Some of these third-party vendors may use non-cookie technologies
            that may not be impacted by browser settings that block cookies.
            Your browser may not permit You to block such technologies. You can
            use the following third-party tools to decline the collection and
            use of information for the purpose of serving You interest-based
            advertising:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              The NAI's opt-out platform:
              <Link href="http://www.networkadvertising.org/choices/">
                http://www.networkadvertising.org/choices/
              </Link>
            </TermsLi>
            <TermsLi>
              The EDAA's opt-out platform
              <Link href="http://www.youronlinechoices.com/">
                http://www.youronlinechoices.com/
              </Link>
            </TermsLi>
            <TermsLi>
              The DAA's opt-out platform:
              <Link href="http://optout.aboutads.info/?c=2&lang=EN">
                http://optout.aboutads.info/?c=2&lang=EN
              </Link>
            </TermsLi>
          </ul>
          <TermsText>
            You may opt-out of all personalized advertising by enabling privacy
            features on Your mobile device such as Limit Ad Tracking (iOS) and
            Opt Out of Ads Personalization (Android). See Your mobile device
            Help system for more information. We may share information, such as
            hashed email addresses (if available) or other online identifiers
            collected on Our Service with these third-party vendors. This allows
            Our third-party vendors to recognize and deliver You ads across
            devices and browsers. To read more about the technologies used by
            these third-party vendors and their cross-device capabilities please
            refer to the Privacy Policy of each vendor listed below.
          </TermsText>
          <TermsText>
            The third-party vendors We may use are, but are not limited to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Google Ads (AdWords) Google Ads (AdWords) remarketing service is
              provided by Google Inc. You can opt-out of Google Analytics for
              Display Advertising and customise the Google Display Network ads
              by visiting the Google Ads Settings page:
              <Link href="http://www.google.com/settings/ads">
                http://www.google.com/settings/ads
              </Link>
              Google also recommends installing the Google Analytics Opt-out
              Browser Add-on -
              <Link href="https://tools.google.com/dlpage/gaoptout">
                https://tools.google.com/dlpage/gaoptout
              </Link>
              - for your web browser. Google Analytics Opt-out Browser Add-on
              provides visitors with the ability to prevent their data from
              being collected and used by Google Analytics. For more information
              on the privacy practices of Google, please visit the Google
              Privacy & Terms web page:
              <Link href="https://policies.google.com/privacy">
                https://policies.google.com/privacy
              </Link>
            </TermsLi>

            <TermsLi>
              Twitter Twitter remarketing service is provided by Twitter Inc.
              You can opt-out from Twitter's interest-based ads by following
              their instructions:
              <Link href="https://support.twitter.com/articles/20170405">
                https://support.twitter.com/articles/20170405
              </Link>
              You can learn more about the privacy practices and policies of
              Twitter by visiting their Privacy Policy page:
              <Link href="https://twitter.com/privacy">
                https://twitter.com/privacy
              </Link>
            </TermsLi>
            <TermsLi>
              Facebook / Meta Facebook or Meta remarketing service is provided
              by Facebook Inc. and Meta Inc. You can learn more about
              interest-based advertising from Facebook by visiting this page:
              <Link href="https://www.facebook.com/help/516147308587266">
                https://www.facebook.com/help/516147308587266
              </Link>
              To opt-out from Facebook's interest-based ads, follow these
              instructions from Facebook:
              <Link href="https://www.facebook.com/help/568137493302217">
                https://www.facebook.com/help/568137493302217
              </Link>
              Facebook adheres to the Self-Regulatory Principles for Online
              Behavioural Advertising established by the Digital Advertising
              Alliance. You can also opt-out from Facebook and other
              participating companies through the Digital Advertising Alliance
              in the USA
              <Link href="http://www.aboutads.info/choices/">
                http://www.aboutads.info/choices/
              </Link>
              , the Digital Advertising Alliance of Canada in Canada
              <Link href="http://youradchoices.ca/">
                http://youradchoices.ca/
              </Link>
              or the European Interactive Digital Advertising Alliance in Europe
              <Link href="http://www.youronlinechoices.eu/">
                http://www.youronlinechoices.eu/
              </Link>
              , or opt-out using your mobile device settings. For more
              information on the privacy practices of Facebook, please visit
              Facebook's Data Policy:
              <Link href="https://www.facebook.com/privacy/explanation">
                https://www.facebook.com/privacy/explanation
              </Link>
            </TermsLi>
            <TermsLi>
              Pinterest Pinterest remarketing service is provided by Pinterest
              Inc. You can opt-out from Pinterest's interest-based ads by
              enabling the "Do Not Track" functionality of your web browser or
              by following Pinterest instructions:
              <Link href="http://help.pinterest.com/en/articles/personalization-and-data">
                http://help.pinterest.com/en/articles/personalization-and-data
              </Link>
              You can learn more about the privacy practices and policies of
              Pinterest by visiting their Privacy Policy page:
              <Link href="https://about.pinterest.com/en/privacy-policy">
                https://about.pinterest.com/en/privacy-policy
              </Link>
            </TermsLi>
          </ul>
          <TermsSubTitle>
            4.5 - Usage, Performance and Miscellaneous
          </TermsSubTitle>
          <TermsText>
            We may use third-party Service Providers to provide better
            improvement of our Service. They may include, but are not limited
            to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Intercom Their Privacy Policy can be viewed at
              <Link href="https://www.intercom.com/legal/privacy">
                https://www.intercom.com/legal/privacy
              </Link>
            </TermsLi>
            <TermsLi>
              Facebook Messenger Their Privacy Policy can be viewed at
              <Link href="https://www.facebook.com/privacy/policy">
                https://www.facebook.com/privacy/policy
              </Link>
            </TermsLi>
            <TermsLi>
              Zendesk Their Privacy Policy can be viewed at
              <Link href="https://www.zendesk.com/company/agreements-and-terms/privacy-notice/">
                https://www.zendesk.com/company/agreements-and-terms/privacy-notice/
              </Link>
            </TermsLi>
            <TermsLi>
              Tawk Their Privacy Policy can be viewed at
              <Link href="https://www.tawk.to/privacy-policy/">
                https://www.tawk.to/privacy-policy/
              </Link>
            </TermsLi>
          </ul>

          <TermsTitle>5 - Links to Other Websites</TermsTitle>

          <TermsText>
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit. We have no
            control over and assume no responsibility for the content, privacy
            policies or practices of any third party sites or services.
          </TermsText>
          <TermsTitle>6 - GDPR Privacy</TermsTitle>
          <TermsSubTitle>
            6.1 - Legal Basis for Processing Personal Data under GDPR
          </TermsSubTitle>

          <TermsText>
            We may process Personal Data under the following conditions:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Consent: You have given Your consent for processing Personal Data
              for one or more specific purposes.
            </TermsLi>
            <TermsLi>
              Performance of a contract: Provision of Personal Data is necessary
              for the performance of an agreement with You and/or for any
              pre-contractual obligations thereof.
            </TermsLi>
            <TermsLi>
              Legal obligations: Processing Personal Data is necessary for
              compliance with a legal obligation to which the Company or
              Operator is subject.
            </TermsLi>
            <TermsLi>
              Vital interests: Processing Personal Data is necessary in order to
              protect Your vital interests or of another natural person.
            </TermsLi>
            <TermsLi>
              Public interests: Processing Personal Data is related to a task
              that is carried out in the public interest or in the exercise of
              official authority vested in the Company or Operator.
            </TermsLi>
            <TermsLi>
              Legitimate interests: Processing Personal Data is necessary for
              the purposes of the legitimate interests pursued by the Company or
              Operator. In any case, the Company or Operator will gladly help to
              clarify the specific legal basis that applies to the processing,
              and in particular whether the provision of Personal Data is a
              statutory or contractual requirement, or a requirement necessary
              to enter into a contract.
            </TermsLi>
          </ul>
          <TermsSubTitle>6.2 - Your Rights under the GDPR</TermsSubTitle>

          <TermsText>
            The Company or Operator undertakes to respect the confidentiality of
            Your Personal Data and to guarantee You can exercise Your rights.
          </TermsText>
          <TermsText>
            You have the right under this Privacy Policy, and by law if You are
            within the EU, to:
          </TermsText>
          <ul
            style={{
              display: 'inline-block',
              listStyle: 'inside',
              marginTop: '20px',
            }}
          >
            <TermsLi>
              Request access to Your Personal Data. The right to access, update
              or delete the information We have on You. Whenever made possible,
              you can access, update or request deletion of Your Personal Data
              directly within Your account settings section. If you are unable
              to perform these actions yourself, please contact Us to assist
              You. This also enables You to receive a copy of the Personal Data
              We hold about You.
            </TermsLi>
            <TermsLi>
              Request correction of the Personal Data that We hold about You.
              You have the right to have any incomplete or inaccurate
              information We hold about You corrected.
            </TermsLi>
            <TermsLi>
              {' '}
              Object to processing of Your Personal Data. This right exists
              where We are relying on a legitimate interest as the legal basis
              for Our processing and there is something about Your particular
              situation, which makes You want to object to our processing of
              Your Personal Data on this ground. You also have the right to
              object where We are processing Your Personal Data for direct
              marketing purposes.
            </TermsLi>
            <TermsLi>
              Request erasure of Your Personal Data. You have the right to ask
              Us to delete or remove Personal Data when there is no good reason
              for Us to continue processing it.
            </TermsLi>
            <TermsLi>
              {' '}
              Request the transfer of Your Personal Data. We will provide to
              You, or to a third-party You have chosen, Your Personal Data in a
              structured, commonly used, machine-readable format. Please note
              that this right only applies to automated information which You
              initially provided consent for Us to use or where We used the
              information to perform a contract with You.
            </TermsLi>
            <TermsLi>
              Withdraw Your consent. You have the right to withdraw Your consent
              on using your Personal Data. If You withdraw Your consent, We may
              not be able to provide You with access to certain specific
              functionalities of the Service.
            </TermsLi>
          </ul>
          <TermsSubTitle>
            6.3 - Exercising of Your GDPR Data Protection Rights
          </TermsSubTitle>

          <TermsText>
            You may exercise Your rights of access, rectification, cancellation
            and opposition by contacting Us. Please note that we may ask You to
            verify Your identity before responding to such requests. If You make
            a request, We will try our best to respond to You as soon as
            possible. You have the right to complain to a Data Protection
            Authority about Our collection and use of Your Personal Data. For
            more information, if You are in the European Economic Area (EEA),
            please contact Your local data protection authority in the EEA.
          </TermsText>

          <TermsTitle>7 - Children's and Minor Users Privacy Rights</TermsTitle>
          <TermsSubTitle>
            7.1 - General Privacy Rights for Children
          </TermsSubTitle>

          <TermsText>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </TermsText>
          <TermsText>
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </TermsText>
          <TermsTitle>8 - Changes to this Privacy Policy</TermsTitle>
          <TermsText>
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </TermsText>
          <TermsText>
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </TermsText>
          <TermsText>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </TermsText>
        </div>
      </TermsWrapper>
    </>
  );
}
