/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/student/login": {
    /** Student Login */
    post: operations["student_login_api_auth_student_login_post"];
  };
  "/api/auth/student/sign-up": {
    /** Student Sign Up */
    post: operations["student_sign_up_api_auth_student_sign_up_post"];
  };
  "/api/auth/student/account-confirmation": {
    /** Student Account Confirmation */
    get: operations["student_account_confirmation_api_auth_student_account_confirmation_get"];
  };
  "/api/auth/student/google-oauth": {
    /** Student Google Auth */
    post: operations["student_google_auth_api_auth_student_google_oauth_post"];
  };
  "/api/auth/coach/login": {
    /** Coach Login */
    post: operations["coach_login_api_auth_coach_login_post"];
  };
  "/api/auth/coach/sign-up": {
    /** Coach Sign Up */
    post: operations["coach_sign_up_api_auth_coach_sign_up_post"];
  };
  "/api/auth/coach/account-confirmation": {
    /** Coach Account Confirmation */
    get: operations["coach_account_confirmation_api_auth_coach_account_confirmation_get"];
  };
  "/api/auth/coach/forgot-password": {
    /** Forgot Password */
    post: operations["forgot_password_api_auth_coach_forgot_password_post"];
  };
  "/api/auth/coach/reset-password/{verification_token}": {
    /** Coach Reset Password */
    post: operations["coach_reset_password_api_auth_coach_reset_password__verification_token__post"];
  };
  "/api/auth/coach/google-oauth": {
    /** Coach Google Auth */
    post: operations["coach_google_auth_api_auth_coach_google_oauth_post"];
  };
  "/": {
    /**
     * Root 
     * @description Redirect to documentation
     */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_coach_login_api_auth_coach_login_post */
    Body_coach_login_api_auth_coach_login_post: {
      /** Grant Type */
      grant_type?: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope 
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string;
      /** Client Secret */
      client_secret?: string;
    };
    /** Body_student_login_api_auth_student_login_post */
    Body_student_login_api_auth_student_login_post: {
      /** Grant Type */
      grant_type?: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope 
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string;
      /** Client Secret */
      client_secret?: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
    };
    /** UserEmail */
    UserEmail: {
      /**
       * Email 
       * Format: email
       */
      email: string;
    };
    /**
     * UserGoogleLogin 
     * @description Scheme for validating user`s sign in via Google OAuth data
     */
    UserGoogleLogin: {
      /** Email */
      email: string;
      /** Username */
      username: string;
      /** Google Openid Key */
      google_openid_key: string;
    };
    /** UserResetPassword */
    UserResetPassword: {
      /** Password */
      password: string;
      /** Password1 */
      password1: string;
    };
    /** UserSignUp */
    UserSignUp: {
      /**
       * Email 
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  student_login_api_auth_student_login_post: {
    /** Student Login */
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_student_login_api_auth_student_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  student_sign_up_api_auth_student_sign_up_post: {
    /** Student Sign Up */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSignUp"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  student_account_confirmation_api_auth_student_account_confirmation_get: {
    /** Student Account Confirmation */
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  student_google_auth_api_auth_student_google_oauth_post: {
    /** Student Google Auth */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserGoogleLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  coach_login_api_auth_coach_login_post: {
    /** Coach Login */
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_coach_login_api_auth_coach_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  coach_sign_up_api_auth_coach_sign_up_post: {
    /** Coach Sign Up */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSignUp"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  coach_account_confirmation_api_auth_coach_account_confirmation_get: {
    /** Coach Account Confirmation */
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forgot_password_api_auth_coach_forgot_password_post: {
    /** Forgot Password */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserEmail"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  coach_reset_password_api_auth_coach_reset_password__verification_token__post: {
    /** Coach Reset Password */
    parameters: {
      path: {
        verification_token: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserResetPassword"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  coach_google_auth_api_auth_coach_google_oauth_post: {
    /** Coach Google Auth */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserGoogleLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root__get: {
    /**
     * Root 
     * @description Redirect to documentation
     */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
}
